// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_logger is a generated GoMock package.
package mock_logger

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	zap "go.uber.org/zap"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// CreateLoggerConfig mocks base method.
func (m *MockConfig) CreateLoggerConfig(level string, colored bool) (zap.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoggerConfig", level, colored)
	ret0, _ := ret[0].(zap.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoggerConfig indicates an expected call of CreateLoggerConfig.
func (mr *MockConfigMockRecorder) CreateLoggerConfig(level, colored interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoggerConfig", reflect.TypeOf((*MockConfig)(nil).CreateLoggerConfig), level, colored)
}
